### ISSUE TITLE
Pass logged in user to custom variable

### ISSUE THREAD

**Issue by GitPuffy** [tetsuo13/Roundcube-Piwik-Tracking-Api-Plugin#2]
It would be great if your plugin could pass the logged in user (user@domain.com) to Piwik in the custom variable field.  For example have the user information passed as custom variable name `userName`

**Comment by tetsuo13** [comment]
I've added a new configuration variable to assign a custom variable slot ID to record the user's email address, `$rcmail_config['piwik_tracking_api_user_email_custom_var']`

Set this to a number from 1 to 5 to use.

This was a really good addition and I couldn't believe it wasn't already there. Thanks for the suggestion!

**Comment by GitPuffy** [comment]
The enhancement works well.  Thank you!
