### ISSUE TITLE
Use setUserId instead of setCustomVariable

### ISSUE THREAD

**Issue by GitPuffy** [tetsuo13/Roundcube-Piwik-Tracking-Api-Plugin#3]
In regards to https://github.com/tetsuo13/Roundcube-Piwik-Tracking-Api-Plugin/commit/e781ec202b8634b6a617263109b9fa9b4c9b3330

I changed the line `$tracker->setCustomVariable($userEmailCustomVar, 'User email', $userEmail);` to

`$tracker->setUserId($userEmail);`

And now Piwik records the email account as the user ID and displays the user account on the main Piwik dashboard view.

I don't know if this is any better in the long run from how you programmed it but I am passing along this tidbit in case you feel it is an even better solution and want to change it in a future release.

Thanks!

**Comment by tetsuo13** [comment]
_This is related to #2._

What you propose may work but it doesn't follow Roundcube's plugin API standards. It's also not guaranteed to work in future versions of this plugin (the config file is parsed in to the same scope as `$tracker` and `$userEmail` but that's not always going to be the case).

**Comment by tetsuo13** [comment]
I misread your comment at first. Your suggestion looks like it may be a better solution than stuffing it into a custom variable. Let me experiment with it to see the differences in Piwik's reporting.

**Comment by tetsuo13** [comment]
I've made the changes to use user ID instead and released version 2.0.0. This is _much_ better than was implemented in #2 since it creates a profile in Piwik.

Thank you!
